import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import { useRouter } from 'next/router'
import { Button, Container } from 'react-bootstrap'
import ClientMiddleware from '@client/middleware'

const Home: NextPage = () => {
	const router = useRouter()
	const { status, data } = useSession()

	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="my-5">
				<h1 className={styles.title}>
					Welcome to Home
				</h1>
				<h4 className="text-center">{data?.user?.name}</h4>
				<Button type="button" onClick={() => signOut()}>Log out</Button>
			</main>
		</Container>
	)
}

export const getServerSideProps = ClientMiddleware.roles([1]).redirects({ [3]: '/customer' }).auth()

export default Home
